"use client";
import {useEffect,useState} from 'react';import {adminApi} from '@/lib/adminApi';
const LABELS:Record<string,string>={'ai.daily_user_limit':'Daily generations per user','ai.daily_ip_limit':'Daily generations per IP','ai.concurrency_limit':'Concurrent generations per API instance','ai.predict_max_output_tokens':'Free-text output token cap','ai.match_max_output_tokens':'Fixture output token cap'};
interface AiSettingRow{key:string;value:number|string}
export default function AiControlsPage(){const [settings,setSettings]=useState<Record<string,number>>({});const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);
  useEffect(()=>{let mounted=true;adminApi.getAiSettings().then((rows:AiSettingRow[])=>{if(mounted)setSettings(Object.fromEntries(rows.map(row=>[row.key,Number(row.value)])))});return()=>{mounted=false}},[]);
  async function save(){setSaving(true);setMessage('');try{setSettings(await adminApi.updateAiSettings(settings));setMessage('AI controls saved and audited.')}catch(error){setMessage(error instanceof Error?error.message:'Save failed')}finally{setSaving(false)}}
  return <div className="space-y-6 max-w-3xl"><div><h1 className="text-2xl font-black text-foreground">AI cost controls</h1><p className="text-sm text-muted mt-1">Operator-owned quotas, concurrency, and output limits</p></div>{message&&<div className="glass rounded-xl p-4 text-sm font-bold">{message}</div>}
    <div className="glass rounded-2xl border border-border/30 p-6 grid sm:grid-cols-2 gap-5">{Object.entries(LABELS).map(([key,label])=><label key={key} className="text-sm font-black text-foreground">{label}<input type="number" min={1} value={settings[key]??''} onChange={e=>setSettings(v=>({...v,[key]:Number(e.target.value)}))} className="mt-2 w-full rounded-xl bg-surface border border-border/40 px-3 py-2 outline-none focus:border-accent"/></label>)}
      <div className="sm:col-span-2"><button disabled={saving||Object.keys(settings).length===0} onClick={save} className="px-5 py-2.5 rounded-xl bg-accent text-white text-sm font-black disabled:opacity-50">{saving?'Saving…':'Save controls'}</button><p className="text-xs text-muted mt-3">Changes require recent administrator MFA authentication and apply within 30 seconds.</p></div></div></div>}
